### ISSUE TITLE
Use picosdk for low level handling?

### ISSUE THREAD

**Issue by bmoneke** [colinoflynn/pico-python#184]
I'm writing the driver for the ps6000a series and encounter several difficulties, because the code has its own quirks.

It's a tedious work to adjust the constants and the data types throughout the whole driver. New error codes make it more difficult to debug, until they are added to the errors list.

As an improvement (and simplification of code maintenance) I propose to use the [picosdk-python-wrappers](https://github.com/picotech/picosdk-python-wrappers) by picotech. Their license allows to use, change, and redistribute the code. For ease of installation, someone made a pypi package.
Obviously, we do not have to change the whole code base at once, but for new devices (and the errors etc.) it could provide a valuable help.

What do you think?

**Comment by colinoflynn** [comment]
This project was started when there was no Python API available at all. I think using the (now existing) picotech supported ones makes sense. I haven't looked at the wrapper in a bit, but previously it was so low-level it made sense to still keep this project since pico-python tries to make a slightly more uniform API. However I'm not very invested in this, so I think if people are interested in pushing more substantial changes we'd welcome suggestions.

**Comment by hmaarrfk** [comment]
Thank you for opening an issue before the large PR.

Given that I no longer have a picoscope, I'm not very interested in drastically changing the backend of this library due to the large risk involved in breaking existing functionality. After investing nearly 9 years into this project, and having others contribute to it, I would be very sad if we broke something they tested and contributed for "maintenance".

Looking at their code, it seems to differ only in the sense that they have a paid developer that is in charge of copy pasting the constants. 

* https://github.com/picotech/picosdk-python-wrappers/blob/master/picosdk/ps3000a.py
* https://github.com/picotech/picosdk-python-wrappers/blob/master/picosdk/constants.py#L129

I'm honestly not too excited about using their wrappers, and exposing the API differently. This feel like something that is best left for each individual developer team. Exposing things as they need.

When writing drivers, there is something to be said about reading the manual. This is mostly why I rejected approaches that would "automatically generate" the constants.

Today, I think users have a good set of options depending on their needs. This project was aimed to be narrow in scope and in its approach. To me, if this means that this project lasts 9 years (first commit in Dec 2013) and get superseded, then that seems like a win to me!

I'm very OK with:
1. Adding functionality following the existing approach.
2. Forking, updating as you wish, and releasing under a different name on PyPi (preferrably that doesn't conflict with this package). We could list your project in the Readme file.
3. Simply using their official SDK.

As somebody developing Python drivers as part of my job (unrelated to PicoTech). I'm curious why you aren't using their python wrappers today? What make you prefer ours?

**Comment by bmoneke** [comment]
Thanks for your comments.

I don't know whether I had found the official wrappers when I searched for picoscope drivers for python or not. At that time I chose pico-python, because it seemed (and still seems) the most natural way to work with an instrument:

- An instance represents a device
- The instance contains all of the necessary properties (e.g. the device handle etc.)
- I do not have to work with c_constants
- Different devices have a unified API

I like these benefits of pico-python and do not want to waste the work done (I contributed as well).

The official API has a single advantage: they make the tedious work of copying constants and variable types.

I do not propose to change the code of all the device or to change the exposed API. I propose to:

- Add the official wrapper as a dependency.
- Base the errorcodes (and maybe other constants) on the official wrapper in order to reduce copy&paste work.
- Allow developers to invoke the official wrappers instead of a direct library call.

This change would reduce the tedious work of turning the manual into constants and c_library_calls (with the correct types), but this package would offer a higher level interface and some thoughts around those library calls.

**Comment by hmaarrfk** [comment]
<details> <summary> Long winded response.... Thank you for your contributions. I didn't mean to dismiss them </summary>


> it seemed (and still seems) the most natural way to work with an instrument

In my opinion, a large part of this is due to the hand crafted nature of the wrappers.

> I like these benefits of pico-python and do not want to waste the work done (I contributed as well).

Big thanks!

> Add the official wrapper as a dependency.

One of the advantages of this library is that it offers an alternative. We both kind list thing with `ctypes.LoadLibrary` why wrap a wrapper? We are both reading the same documentation.

> Allow developers to invoke the official wrappers instead of a direct library call.

But why..... we both use ctypes.

> turning the manual into constants and c_library_calls (with the correct types)

I really do see this as an advantage.

The large ones were generated through copy paste, search and replace.

I really am excited about their drivers. I added their reference about [4 years ago](https://github.com/colinoflynn/pico-python/commit/6fec0ee70cc8502296315f03419213f95c290490) thinking then that this project was dead!
</details>

All in all, I guess the truth is that my "review" process has become a light "visual diff" between one driver and the previous one. Maybe it is sad to say, but I just don't have the mental capacity to "learn" a new organization. Even 9 years later, the old organization still feels familiar to me. I guess I'm officially old.... 

It seems that Colin might be able to review????

I understand the painful nature of building a "second" driver, for hardware that is "slightly better".
I'm not sure there really is a better way than to struggle with bugs through the process.
It really makes you intimately knowledgeable of the underlying device. You've already improved the 4000 series driver quite a bit when pushing what we used to have!

**Comment by hmaarrfk** [comment]
<details> <summary> more history </summary>

I really did feel strongly in the past, that reading the documentation was the way to go.

https://github.com/colinoflynn/pico-python/pull/109/files#diff-5e972a27e969f4fb97a1cc2d2f68080a5e14776a29b645836eaf76dbfb0c4802R9-R10

This stance hasn't changed much for me 😞 
</details>

**Comment by bmoneke** [comment]
In the end, it's about using constants. These we can plainly copy, therefore, I do not see the large benefit of introducing this dependency anymore.
